export const ADD_WISHLIST_LOADING = 'ADD_WISHLIST_LOADING';
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAIL = 'ADD_WISHLIST_FAIL';

export const FETCH_WISHLIST_LOADING = 'FETCH_WISHLIST_LOADING';
export const FETCH_WISHLIST_SUCCESS = 'FETCH_WISHLIST_SUCCESS';
export const FETCH_WISHLIST_FAIL = 'FETCH_WISHLIST_FAIL';

export const REMOVE_WISHLIST_LOADING = 'REMOVE_WISHLIST_LOADING';
export const REMOVE_WISHLIST_SUCCESS = 'REMOVE_WISHLIST_SUCCESS';
export const REMOVE_WISHLIST_FAIL = 'REMOVE_WISHLIST_FAIL';
